### ISSUE TITLE
ContextMenuIcon.filter is not optional

### ISSUE THREAD

**Issue by kamejosh** [owlbear-rodeo/sdk#2]
# Summary

https://github.com/owlbear-rodeo/sdk/blob/bc47df4888bab7dbe0080e108d3a1f114e04cb11/src/types/ContextMenu.ts#L23

indicates that the `filter` property is optional but when not using the filter property the following error ist recieved:

```
{
  "name": "ValidationError",
  "message": "\"icons[0].filter\" is required",
  "details": [
    {
      "message": "\"icons[0].filter\" is required",
      "path": [
        "icons",
        0,
        "filter"
      ],
      "type": "any.required",
      "context": {
        "label": "icons[0].filter",
        "key": "filter"
      }
    }
  ]
}
```

# Expected Behavior

Properties defined as optional should be optional

**Comment by mitchemmc** [comment]
Should be fixed in https://github.com/owlbear-rodeo/sdk/releases/tag/v1.3.9
