### ISSUE TITLE
bug: OBR.player.getMetadata() resolves to empty object after page reload

### ISSUE THREAD

**Issue by resident-uhlig** [owlbear-rodeo/sdk#9]
Hello, I think this is a bug. If not, please explain what I did wrong or tell me where it is explained.

**How to reproduce**

When using `OBR.player.getMetadata()` after a page reload, then the result is always an empty object.

1. Install an extension with this javascript loaded:
```javascript
// popover.js

import OBR from "@owlbear-rodeo/sdk";

OBR.onReady(async () => {
  // check state after reload
  console.log(OBR.player.id, await OBR.player.getMetadata());

  // set to something
  await OBR.player.setMetadata({"some": "thing"});

  // check state after setting to something
  console.log(OBR.player.id, await OBR.player.getMetadata());
});
```
2. Reload the **frame** (right click inside the popover, then "reload frame")
3. Reload the **page** (click the reload page button of the browser next to the address bar)

**Further details**

I tested this exact code during development of my own extension, so the URL to the popover was something like <https://localhost:8080/popover.html> at that time. However, I can observe the same behaviour (with more complex code) when I host the extension using GitLab pages.

In contrast, the function for the *room* `OBR.room.getMetadata` works just fine.

@owlbear-rodeo/sdk version: 2.3.0

**Expected**

```
a911366f-8676-4f30-9bde-8492420babcd {}
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
(frame reload)
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
(page reload)
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
```

**Actual**

```
a911366f-8676-4f30-9bde-8492420babcd {}
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
(frame reload)
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
(page reload)
a911366f-8676-4f30-9bde-8492420babcd {}
a911366f-8676-4f30-9bde-8492420babcd {some: 'thing'}
```

Please note the difference in the second to last line. It seems the metadata is remembered after *frame* reload but not after *page* reload.

**Comment by nthouliss** [comment]
Hi, this isn't a bug. It's behaving as expected. Here's an explanation on why it behaves this way. I'm quoting @mitchemmc from our Discord. 

> Player metadata isn't saved between refreshes
> 
> Below is some of the technical differences between types of metadata.
> 
> Networking:
> The metadata for a scene or scene item uses a CRDT so it is network resilient.
> The metadata for a player uses a simple CRDT but can only be updated by one person at a time so collisions aren't a concern there.
> Room metadata doesn't use any network resiliency and is last writer wins. Which is why it is generally meant for small values with very low frequency updates.
> 
> Size:
> Metadata for a scene uses the users storage quota.
> Each individual update to the scene and player metadata is limited by the max update size (64kb).
> The room metadata has a max size of 16kB shared across all extensions.
> 
> Other Differences:
> Updates to the scene metadata are added to the undo stack of the user. This means a Ctrl+Z will undo changes made.
> Player metadata is per connection. This means that refreshing the page will reset the metadata. 
> 

I hope this helps clarify player metadata a little, it's also good to note that a player != user. If a user has two browser open to a room then they are in the room twice.

**Comment by hypergig** [comment]
would it be possible to drop this information in the SDK docs?
